<div class="row">
    <div class="well col-md-offset-4 col-md-4">
        <h4 class="text-center">Log in</h4>
        <form method="post">
            <input name="email" type="text" class="form-control" placeholder="Email">
            <br>
            <input name="password" type="password" class="form-control" placeholder="Password">
            <br>
            <p class="text-right">
                <button class="btn btn-default">Log in</button>
            </p>
        </form>
    </div>
</div>