<div class="row">
    <div class="well col-md-offset-4 col-md-4">
        <div>Register account</div>
        <form method="post">
            <input name="name" type="text" class="form-control" placeholder="Name">
            <input name="email" type="text" class="form-control" placeholder="Email">
            <input name="password" type="text" class="form-control" placeholder="Password">
            <div class="row">
                <label for="role_waiter" class="col-md-6">
                    <input id="role_waiter" name="role" type="radio" class="form-control" value="waiter">
                    <span>Waiter</span>
                </label>
                <label for="role_waiter" class="col-md-6">
                    <input id="role_cook" name="role" type="radio" class="form-control" value="cook">
                    <span>Cook</span>
                </label>
            </div>
            <p class="text-right">
                <button class="btn btn-default">Register</button>
            </p>
        </form>
    </div>
</div>