<div class="row">
    <div class="col-md-8"></div>
    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <?= $this->order->getName(); ?>
            </div>
            <div class="panel-body">
                <form action="<?= $this->url('dashboard', ['action' => 'order']); ?>" id="order_<?= $this->order->getId(); ?>">
                    <input type="hidden" name="dish" value="<?= $this->order->getDish(); ?>">
                    <input type="hidden" name="name" value="<?= $this->order->getName(); ?>">
                    <input type="hidden" name="id" value="<?= $this->order->getId(); ?>">
                    Dish: <b><?= $this->order->getDish(); ?></b>
                    <br>
                    Cook: <b><?= $this->order->getCook()->getName(); ?></b>
                    <br>
                    Created: <b><?= $this->order->getCreated()->format('H:i:s'); ?></b>
                    <br>
                    Minutes: <?= $this->order->getMinutes(); ?>
                    <input type="hidden" name="status" value="<?= \Application\Entity\Order::STATUS_CLOSED; ?>">
                    <br>
                    <a class="btn btn-success get-order" data-order="<?= $this->order->getId(); ?>">Give</a>
                </form>
            </div>
        </div>
    </div>
</div>