<div class="row">
    <div class="col-md-4">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <?= $this->order->getName(); ?>
            </div>
            <div class="panel-body">
                Dish: <b><?= $this->order->getDish(); ?></b>
                <br>
                Created: <b><?= $this->order->getCreated()->format('H:i:s'); ?></b>
            </div>
        </div>
    </div>
    <div class="col-md-8"></div>
</div>