<div class="row">
    <div class="well col-md-offset-4 col-md-4">
        <div>Create order</div>
        <form method="post">
            <input name="name" type="text" class="form-control" placeholder="Name">
            <input name="dish" type="text" class="form-control" placeholder="Dish">
            <p class="text-right">
                <button class="btn btn-default">Log in</button>
            </p>
        </form>
    </div>
</div>