<div class="row">
    <div class="well col-md-offset-4 col-md-4">
        <h4 class="text text-center">Create order</h4>
        <form method="post">
            <input name="name" type="text" class="form-control" placeholder="Name">
            <br>
            <input name="dish" type="text" class="form-control" placeholder="Dish">
            <br>
            <div class="row">
                <div class=" col-md-9 text-left text-muted">
                    You will be redirected to dashboard
                </div>
                <div class="col-md-3 text-right">
                    <button class="btn btn-default">Create</button>
                </div>
            </div>
        </form>
    </div>
</div>