<div class="row">
    <div class="col-md-8"></div>
    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <?= $this->order->getName(); ?>
            </div>
            <div class="panel-body">
                Dish: <b><?= $this->order->getDish(); ?></b>
                <br>
                Waiter: <b><?= $this->order->getWaiter()->getName(); ?></b>
                <br>
                Created: <b><?= $this->order->getCreated()->format('H:i:s'); ?></b>
                <br>
                Minutes: <?= $this->order->getMinutes(); ?>
            </div>
        </div>
    </div>
</div>