<a href="<?= $this->url('dashboard', ['action' => 'order']); ?>" class="btn btn-primary">Create Order</a>
<?= $this->partial('partial/index/general/heading.phtml'); ?>
<?php foreach ($this->orders as $order) : ?>
        <?php /** @var \Application\Entity\Order $order */ ?>
        <?= $this->partial('partial/index/waiter/' . $order->getStatus() . '.phtml', ['order' => $order]); ?>
<?php endforeach; ?>
